### ISSUE TITLE
Corregir error para async_deliver_hook

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5943]
Revisando la consola encontre este error que esta dando. Al parecer se esta llamando un delayed action pasandole un decimal y eso no lo acepta Redis porque no es "json serializable". 

https://github.com/breatheco-de/apiv2/blob/ce54122d75ab59064710295352b99db2d3074212/breathecode/notify/tasks.py#L99

```bash
2023-08-29T13:43:53.919633+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,919] breathecode.marketing.tasks INFO     Starting persist_single_lead
2023-08-29T13:43:53.943488+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,943] breathecode.marketing.actions DEBUG    found 1 automations
2023-08-29T13:43:53.944917+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,944] breathecode.marketing.actions INFO     found automations
2023-08-29T13:43:53.944995+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,944] breathecode.marketing.actions INFO     [48]
2023-08-29T13:43:53.952750+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,952] breathecode.marketing.actions INFO     found tags
2023-08-29T13:43:53.952813+00:00 app[celeryworker.1]: [2023-08-29 13:43:53,952] breathecode.marketing.actions INFO     {'request_more_info'}
2023-08-29T13:43:54.021033+00:00 app[celeryworker.1]: [2023-08-29 13:43:54,020] breathecode.marketing.actions INFO     ready to send contact with following details: {'email': 'xxxxx@gmail.com', 'first_name': 'xxx xxx', 'last_name': '', 'phone': '+xxxx', 'field[60,0]': 'https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack?utm_source=fb&utm_medium=ppc&utm_campaign=23857560505000343&utm_id=23857560505000343&utm_term=23857560505020343&utm_content=23857560505050343', 'field[18,0]': 'caracas-venezuela', 'field[2,0]': 'full-stack', 'field[16,0]': 'en', 'field[19,0]': 'Venezuela', 'field[33,0]': '23857560505000343', 'field[59,0]': 'fb', 'field[35,0]': '23857560505050343', 'field[36,0]': 'ppc', 'field[67,0]': None, 'field[66,0]': None, 'field[65,0]': '23857560505020343', 'field[45,0]': None, 'field[13,0]': None, 'field[26,0]': None, 'field[46,0]': None, 'field[27,0]': None}
2023-08-29T13:43:54.426288+00:00 app[celeryworker.1]: [2023-08-29 13:43:54,425: ERROR/ForkPoolWorker-2] Task breathecode.notify.tasks.async_deliver_hook[6a319a7a-52e7-460d-9100-df23b9419471] raised unexpected: TypeError('Object of type Decimal is not JSON serializable')
2023-08-29T13:43:54.426310+00:00 app[celeryworker.1]: Traceback (most recent call last):
2023-08-29T13:43:54.426310+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2023-08-29T13:43:54.426311+00:00 app[celeryworker.1]:     R = retval = fun(*args, **kwargs)
2023-08-29T13:43:54.426311+00:00 app[celeryworker.1]:                  ^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426311+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023-08-29T13:43:54.426311+00:00 app[celeryworker.1]:     return self.run(*args, **kwargs)
2023-08-29T13:43:54.426311+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426312+00:00 app[celeryworker.1]:   File "/app/breathecode/notify/tasks.py", line 137, in async_deliver_hook
2023-08-29T13:43:54.426312+00:00 app[celeryworker.1]:     hook.save()
2023-08-29T13:43:54.426312+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save
2023-08-29T13:43:54.426313+00:00 app[celeryworker.1]:     self.save_base(using=using, force_insert=force_insert,
2023-08-29T13:43:54.426313+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:     updated = self._save_table(
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:               ^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 858, in _save_table
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:     updated = self._do_update(base_qs, using, pk_val, values, update_fields,
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 912, in _do_update
2023-08-29T13:43:54.426314+00:00 app[celeryworker.1]:     return filtered._update(values) > 0
2023-08-29T13:43:54.426315+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426315+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/query.py", line 802, in _update
2023-08-29T13:43:54.426315+00:00 app[celeryworker.1]:     return query.get_compiler(self.db).execute_sql(CURSOR)
2023-08-29T13:43:54.426315+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:     cursor = super().execute_sql(result_type)
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:     sql, params = self.as_sql()
2023-08-29T13:43:54.426316+00:00 app[celeryworker.1]:                   ^^^^^^^^^^^^^
2023-08-29T13:43:54.426317+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1525, in as_sql
2023-08-29T13:43:54.426317+00:00 app[celeryworker.1]:     val = field.get_db_prep_save(val, connection=self.connection)
2023-08-29T13:43:54.426317+00:00 app[celeryworker.1]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426317+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
2023-08-29T13:43:54.426317+00:00 app[celeryworker.1]:     return self.get_db_prep_value(value, connection=connection, prepared=False)
2023-08-29T13:43:54.426318+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426318+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 837, in get_db_prep_value
2023-08-29T13:43:54.426318+00:00 app[celeryworker.1]:     value = self.get_prep_value(value)
2023-08-29T13:43:54.426318+00:00 app[celeryworker.1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426318+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/fields/json.py", line 93, in get_prep_value
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:     return json.dumps(value, cls=self.encoder)
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/json/__init__.py", line 231, in dumps
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:     return _default_encoder.encode(obj)
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426319+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/json/encoder.py", line 200, in encode
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:     chunks = self.iterencode(o, _one_shot=True)
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/json/encoder.py", line 258, in iterencode
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:     return _iterencode(o, 0)
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/json/encoder.py", line 180, in default
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]:     raise TypeError(f'Object of type {o.__class__.__name__} '
2023-08-29T13:43:54.426320+00:00 app[celeryworker.1]: TypeError: Object of type Decimal is not JSON serializable
2023-08-29T13:43:54.581105+00:00 app[celeryworker.1]: [2023-08-29 13:43:54,581: WARNING/ForkPoolWorker-2] Got unexpected status code from Rollbar api: 403
2023-08-29T13:43:54.581107+00:00 app[celeryworker.1]: Response:
2023-08-29T13:43:54.581107+00:00 app[celeryworker.1]: {
2023-08-29T13:43:54.581107+00:00 app[celeryworker.1]:   "err": 1,
2023-08-29T13:43:54.581108+00:00 app[celeryworker.1]:   "message": "access token not found: c22ced00f3c041e6ac16d8530cd295eb"
2023-08-29T13:43:54.581108+00:00 app[celeryworker.1]: }
2023-08-29T13:43:54.581553+00:00 app[celeryworker.1]: [2023-08-29 13:43:54,581: ERROR/ForkPoolWorker-2] Exception while posting item ApiError('access token not found: c22ced00f3c041e6ac16d8530cd295eb')
2023-08-29T13:43:54.581554+00:00 app[celeryworker.1]: Traceback (most recent call last):
2023-08-29T13:43:54.581554+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/rollbar/__init__.py", line 1497, in _send_payload
2023-08-29T13:43:54.581555+00:00 app[celeryworker.1]:     _post_api('item/', payload_str, access_token=access_token)
2023-08-29T13:43:54.581555+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/rollbar/__init__.py", line 1554, in _post_api
2023-08-29T13:43:54.581556+00:00 app[celeryworker.1]:     return _parse_response(path, SETTINGS['access_token'], payload_str, resp)
2023-08-29T13:43:54.581556+00:00 app[celeryworker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T13:43:54.581556+00:00 app[celeryworker.1]:   File "/app/.heroku/python/lib/python3.11/site-packages/rollbar/__init__.py", line 1733, in _parse_response
2023-08-29T13:43:54.581557+00:00 app[celeryworker.1]:     raise ApiError(json_data.get('message') or 'Unknown error')
2023-08-29T13:43:54.581559+00:00 app[celeryworker.1]: rollbar.ApiError: access token not found: c22ced00f3c041e6ac16d8530cd295eb
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1081

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/blob/e62973ea32d1292cd32c187f5c26e718bb34006b/breathecode/notify/tasks.py#L103

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/blob/5dac22060e8aeeab7a03ae470244da4305ba5432/breathecode/utils/decorators/task.py#L21
