### ISSUE TITLE
Research the following error

### ISSUE THREAD

**Issue by Charlytoc** [breatheco-de/breatheco-de#5999]
{'question': 'What do you know about  σαῦρος sauros', 'document': None, 'purpose': '1'}
2023-09-06 21:08:35,106 breathecode.conversation.classes DEBUG    Getting existing DB or creating
2023-09-06 21:08:35,106 breathecode.conversation.classes DEBUG    Initializing Chroma Manager
2023-09-06 21:08:36,053 django.request ERROR    Internal Server Error: /v1/conversation/answer/
Traceback (most recent call last):
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 223, in query
    return self._client._query(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/api/local.py", line 457, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 613, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 296, in get_nearest_neighbors
    database_labels, distances = self._index.knn_query(
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/rigobot/breathecode/conversation/views.py", line 196, in post
    context = manager.run(question=question)
  File "/workspace/rigobot/breathecode/conversation/classes.py", line 323, in run
    return self.chain.run(question)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 236, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 376, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 229, in similarity_search_with_score
    results = self.__query_collection(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/utils.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 128, in __query_collection
    except chromadb.errors.NotEnoughElementsException:
AttributeError: module 'chromadb.errors' has no attribute 'NotEnoughElementsException'
[06/Sep/2023 21:08:36] "POST /v1/conversation/answer/ HTTP/1.1" 500 241919

**Comment by Charlytoc** [comment]
The error happens when adding a huge website

Traceback (most recent call last):
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/rigobot/breathecode/finetuning/views.py", line 231, in bookmark_website
    website.purposes.set(purposes)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 1159, in _add_items
    signals.m2m_changed.send(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/workspace/rigobot/breathecode/finetuning/signals.py", line 185, in website_purpose_changed
    manage_embeddings_for_index(index_id=index.id, changelog=changelog)
  File "/workspace/rigobot/breathecode/conversation/actions.py", line 81, in manage_embeddings_for_index
    manager.process_changelog(changelog)
  File "/workspace/rigobot/breathecode/conversation/classes.py", line 251, in process_changelog
    self.add_content_with_metadata(content=content, metadata=metadata)
  File "/workspace/rigobot/breathecode/conversation/classes.py", line 275, in add_content_with_metadata
    self._add_documents_to_collection(documents=splits)
  File "/workspace/rigobot/breathecode/conversation/classes.py", line 297, in _add_documents_to_collection
    self.vectordb._collection.add(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 100, in add
    self._client._add(
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/api/local.py", line 260, in _add
    self._db.add_incremental(collection_id, added_uuids, embeddings)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 639, in add_incremental
    index.add(ids, embeddings)
  File "/workspace/rigobot/.venv/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 177, in add
    self._index.add_items(embeddings, labels)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1401,) + inhomogeneous part.

**Comment by Charlytoc** [comment]
Try with https://en.wikipedia.org/wiki/Dinosaur
